version: '3.9'
services:
  database:
    container_name: lemondb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
  server:
    container_name: lemon-mart-server
    build: server
    restart: always
    environment:
      MONGO_URI: mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - database
volumes:
  mongodb:
